"""Recreate migrations

Revision ID: 1175d63265ef
Revises: 
Create Date: 2024-12-10 19:49:54.561297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1175d63265ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bericht')
    with op.batch_alter_table('klus', schema=None) as batch_op:
        batch_op.alter_column('beschrijving',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('categorie',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('locatie',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('vergoeding',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_constraint('klus_categorie_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categorie', ['categorie'], ['categorie'])

    with op.batch_alter_table('persoon', schema=None) as batch_op:
        batch_op.drop_column('is_active_flag')

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vriendelijkheid_zoeker', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('communicatie_zoeker', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('algemene_ervaring_zoeker', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vriendelijkheid_aanbieder', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gastvrijheid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('communicatie_aanbieder', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('algemene_ervaring_aanbieder', sa.Integer(), nullable=True))
        batch_op.alter_column('kluszoeker_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('tijdigheid',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('kwaliteit',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('klusaanbieder_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('betrouwbaarheid',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('algemene_ervaring')
        batch_op.drop_column('communicatie')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('communicatie', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('algemene_ervaring', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.alter_column('betrouwbaarheid',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('klusaanbieder_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('kwaliteit',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('tijdigheid',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('kluszoeker_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.drop_column('algemene_ervaring_aanbieder')
        batch_op.drop_column('communicatie_aanbieder')
        batch_op.drop_column('gastvrijheid')
        batch_op.drop_column('vriendelijkheid_aanbieder')
        batch_op.drop_column('algemene_ervaring_zoeker')
        batch_op.drop_column('communicatie_zoeker')
        batch_op.drop_column('vriendelijkheid_zoeker')

    with op.batch_alter_table('persoon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active_flag', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('klus', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('klus_categorie_fkey', 'categorie', ['categorie'], ['categorie'], ondelete='SET NULL')
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('vergoeding',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('locatie',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('categorie',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('beschrijving',
               existing_type=sa.TEXT(),
               nullable=True)

    op.create_table('bericht',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('afzender_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('ontvanger_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('klusnummer', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('inhoud', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('verzonden_op', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['afzender_id'], ['persoon.idnummer'], name='bericht_afzender_id_fkey'),
    sa.ForeignKeyConstraint(['klusnummer'], ['klus.klusnummer'], name='bericht_klusnummer_fkey'),
    sa.ForeignKeyConstraint(['ontvanger_id'], ['persoon.idnummer'], name='bericht_ontvanger_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='bericht_pkey')
    )
    # ### end Alembic commands ###
