"""Add Chat model

Revision ID: 3a708780d1f0
Revises: cbe30a00be35
Create Date: 2024-12-10 09:56:41.153566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a708780d1f0'
down_revision = 'cbe30a00be35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('klus', schema=None) as batch_op:
        batch_op.alter_column('categorie',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('locatie',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('beschrijving',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('vergoeding',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_constraint('klus_categorie_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categorie', ['categorie'], ['categorie'], ondelete='SET NULL')
        batch_op.drop_column('voltooid_op')

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_constraint('rating_kluszoeker_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'persoon', ['kluszoeker_id'], ['idnummer'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('rating_kluszoeker_id_fkey', 'persoon', ['kluszoeker_id'], ['idnummer'], ondelete='CASCADE')

    with op.batch_alter_table('klus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voltooid_op', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('klus_categorie_fkey', 'categorie', ['categorie'], ['categorie'])
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('vergoeding',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('beschrijving',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('locatie',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('categorie',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
