"""empty message

Revision ID: 5c8ce6b79051
Revises: cbe30a00be35
Create Date: 2024-12-10 11:53:00.612308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c8ce6b79051'
down_revision = 'cbe30a00be35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatbericht')
    op.drop_table('users')
    op.drop_table('chat')
    with op.batch_alter_table('klus', schema=None) as batch_op:
        batch_op.alter_column('categorie',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('locatie',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('beschrijving',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('vergoeding',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_constraint('klus_categorie_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categorie', ['categorie'], ['categorie'], ondelete='SET NULL')
        batch_op.drop_column('voltooid_op')

    with op.batch_alter_table('persoon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active_flag', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persoon', schema=None) as batch_op:
        batch_op.drop_column('is_active_flag')

    with op.batch_alter_table('klus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voltooid_op', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('klus_categorie_fkey', 'categorie', ['categorie'], ['categorie'])
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('vergoeding',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('beschrijving',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('locatie',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('categorie',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    op.create_table('chat',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('klusnummer', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('receiver_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['klusnummer'], ['klus.klusnummer'], name='chat_klusnummer_fkey'),
    sa.ForeignKeyConstraint(['receiver_id'], ['persoon.idnummer'], name='chat_receiver_id_fkey'),
    sa.ForeignKeyConstraint(['sender_id'], ['persoon.idnummer'], name='chat_sender_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chat_pkey')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    sa.UniqueConstraint('username', name='users_username_key')
    )
    op.create_table('chatbericht',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bericht', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tijd', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('afzender_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('ontvanger_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('klusnummer', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['afzender_id'], ['persoon.idnummer'], name='chatbericht_afzender_id_fkey'),
    sa.ForeignKeyConstraint(['klusnummer'], ['klus.klusnummer'], name='chatbericht_klusnummer_fkey'),
    sa.ForeignKeyConstraint(['ontvanger_id'], ['persoon.idnummer'], name='chatbericht_ontvanger_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chatbericht_pkey')
    )
    # ### end Alembic commands ###
