"""Add ondelete cascade to CategorieStatistiek

Revision ID: 5f9504c1df07
Revises: 68303ebb25e1
Create Date: 2024-12-08 16:36:24.527391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9504c1df07'
down_revision = '68303ebb25e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorie_statistiek', schema=None) as batch_op:
        batch_op.drop_constraint('categorie_statistiek_categorie_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categorie', ['categorie'], ['categorie'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorie_statistiek', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('categorie_statistiek_categorie_fkey', 'categorie', ['categorie'], ['categorie'], ondelete='CASCADE')

    # ### end Alembic commands ###
