"""Add ON DELETE CASCADE to CategorieStatistiek

Revision ID: 68303ebb25e1
Revises: 68c772525458
Create Date: 2024-12-08 16:32:29.825617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68303ebb25e1'
down_revision = '68c772525458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voltooide_klussen')
    with op.batch_alter_table('categorie_statistiek', schema=None) as batch_op:
        batch_op.drop_constraint('categorie_statistiek_categorie_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categorie', ['categorie'], ['categorie'], ondelete='CASCADE')

    with op.batch_alter_table('klus', schema=None) as batch_op:
        batch_op.alter_column('categorie',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_constraint('klus_categorie_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categorie', ['categorie'], ['categorie'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('klus', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('klus_categorie_fkey', 'categorie', ['categorie'], ['categorie'], ondelete='SET NULL')
        batch_op.alter_column('categorie',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('categorie_statistiek', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('categorie_statistiek_categorie_fkey', 'categorie', ['categorie'], ['categorie'])

    op.create_table('voltooide_klussen',
    sa.Column('persoon_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('klus_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['klus_id'], ['klus.klusnummer'], name='voltooide_klussen_klus_id_fkey'),
    sa.ForeignKeyConstraint(['persoon_id'], ['persoon.idnummer'], name='voltooide_klussen_persoon_id_fkey'),
    sa.PrimaryKeyConstraint('persoon_id', 'klus_id', name='voltooide_klussen_pkey')
    )
    # ### end Alembic commands ###
