"""Add voltooid_op to Klus

Revision ID: 70a615525aed
Revises: 3a708780d1f0
Create Date: 2024-12-10 10:22:38.131030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a615525aed'
down_revision = '3a708780d1f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('klus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voltooid_op', sa.DateTime(), nullable=True))
        batch_op.alter_column('beschrijving',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('categorie',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('locatie',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('vergoeding',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_constraint('klus_categorie_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categorie', ['categorie'], ['categorie'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('klus', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('klus_categorie_fkey', 'categorie', ['categorie'], ['categorie'], ondelete='SET NULL')
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('vergoeding',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('locatie',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('categorie',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('beschrijving',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('voltooid_op')

    # ### end Alembic commands ###
