"""Add voltooid_op field to Klus

Revision ID: a4d70130d0e7
Revises: 5f9504c1df07
Create Date: 2024-12-08 17:20:32.952450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d70130d0e7'
down_revision = '5f9504c1df07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('klus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voltooid_op', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('klus', schema=None) as batch_op:
        batch_op.drop_column('voltooid_op')

    # ### end Alembic commands ###
