"""Remove kluszoeker_id from Klus

Revision ID: cd48582910cb
Revises: 1241a98bbe5a
Create Date: 2024-12-16 21:03:47.318181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd48582910cb'
down_revision = '1241a98bbe5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bericht', schema=None) as batch_op:
        batch_op.drop_column('gelezen')

    with op.batch_alter_table('klus', schema=None) as batch_op:
        batch_op.drop_constraint('klus_kluszoeker_id_fkey', type_='foreignkey')
        batch_op.drop_column('kluszoeker_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('klus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kluszoeker_id', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('klus_kluszoeker_id_fkey', 'persoon', ['kluszoeker_id'], ['idnummer'])

    with op.batch_alter_table('bericht', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gelezen', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
